# Generated by Django 2.2.6 on 2019-11-07 05:40

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='students/image'),
        ),
    ]
